name: 'pmemkv-bench CI'
description: 'pmemkv-bench'
inputs:
  entrypoint_params:  # id of input
    description: 'Parameters for Docker entrypoint'
    required: true
runs:
  using: 'docker'
  image: '../Dockerfile'
  env:
    TEST_PATH: '/tmp/pmemkv-bench'
  args:
    - ${{ inputs.entrypoint_params }}
