# SPDX-License-Identifier: Apache-2.0
# Copyright 2016-2021, Intel Corporation

FROM ubuntu:20.04
MAINTAINER szymon.romik@intel.com

RUN apt update && \
	DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
	libpmemkv-dev \
	libpmempool-dev \
	make \
	g++ \
	pkg-config \
	clang-format-10 \
	python3-pymongo \
 && rm -rf /var/lib/apt/lists/*
